# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-09 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_column', '0003_add_attributes_fields_20191019_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='width_lg',
            field=models.CharField(blank=True, choices=[('', '--'), ('col-lg-10pct', '10%'), ('col-lg-25pct', '25%'), ('col-lg-33pct', '33%'), ('col-lg-50pct', '50%'), ('col-lg-66pct', '66%'), ('col-lg-75pct', '75%'), ('col-lg-100pct', '100%')], default='', max_length=50, verbose_name='medium width (>= 1200px)'),
        ),
        migrations.AddField(
            model_name='column',
            name='width_md',
            field=models.CharField(blank=True, choices=[('', '--'), ('col-md-10pct', '10%'), ('col-md-25pct', '25%'), ('col-md-33pct', '33%'), ('col-md-50pct', '50%'), ('col-md-66pct', '66%'), ('col-md-75pct', '75%'), ('col-md-100pct', '100%')], default='', max_length=50, verbose_name='medium width (>= 992px)'),
        ),
        migrations.AddField(
            model_name='column',
            name='width_xs',
            field=models.CharField(choices=[('col-xs-10pct', '10%'), ('col-xs-25pct', '25%'), ('col-xs-33pct', '33%'), ('col-xs-50pct', '50%'), ('col-xs-66pct', '66%'), ('col-xs-75pct', '75%'), ('col-xs-100pct', '100%')], default='col-xs-10pct', max_length=50, verbose_name='extra small width (< 768px)'),
        ),
        migrations.AlterField(
            model_name='column',
            name='width',
            field=models.CharField(choices=[('10%', '10%'), ('25%', '25%'), ('33.33%', '33%'), ('50%', '50%'), ('66.66%', '66%'), ('75%', '75%'), ('100%', '100%')], default='10%', max_length=50, verbose_name='small width (>= 768px)'),
        ),
    ]
